version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: yt
      POSTGRES_PASSWORD: yt
      POSTGRES_DB: yt
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
  api:
    build: .
    ports: ["8000:8000"]
    env_file:
      - ./.env.local        # dev-only
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
    depends_on: [db]

volumes: { pgdata: {} }