services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: yt
      POSTGRES_PASSWORD: yt
      POSTGRES_DB: yt
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    env_file:
      - ./.env.local
    volumes:
      # mount your local source into the same path the image uses (/app)
      - ./:/app
    depends_on: [db]
    # optional niceties
    environment:
      PYTHONUNBUFFERED: "1"
    tty: true
    stdin_open: true

volumes:
  pgdata: {}
