export {
  LOCATION_MAP,
  SUPPORTED_LOCATIONS,
  DataForSEOError,
  validatePhrase,
  validateKeywords,
  validateLocation,
  generateRequestHash,
  calculateDifficultyHeuristic,
  parseNumeric,
  parseInteger,
  parseMonthlyTrend,
  parseCompetitionLevel,
  isRestrictedCategoryError,
  type LocationCode,
} from "@/lib/adapters/dataforseo/utils";
